name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh $EC2_USER@$EC2_HOST 'bash -s' << 'ENDSSH'
            # Navigate to project directory
            cd /home/ubuntu/personal-website

            # Pull latest changes
            git pull

            # Activate virtual environment and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # Copy production environment file if it doesn't exist
            if [ ! -f .env.production ]; then
              cp .env.example .env.production
            fi

            # Restart the Flask application
            sudo systemctl restart flask-app

            # Check service status
            sudo systemctl status flask-app --no-pager
          ENDSSH 